name: flutter_overlay_apps
description: Android plugin for displaying flutter widgets over other apps
version: 1.0.2
homepage: https://github.com/EddieKamau/flutter_overlay_apps

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:

  plugin:
    platforms:
      android:
        package: com.phan_tech.flutter_overlay_apps
        pluginClass: FlutterOverlayAppsPlugin

